# Generated by Django 5.0 on 2023-12-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jobskrsignup',
        ),
    ]
