# Generated by Django 5.0 on 2023-12-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phonenumbwe',
            new_name='phonenumber',
        ),
    ]
