# Generated by Django 5.0 on 2023-12-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_phonenumbwe_contact_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
