# Generated by Django 5.0 on 2023-12-29 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='status',
        ),
    ]
