# Generated by Django 5.0 on 2023-12-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
