# Generated by Django 5.0 on 2023-12-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_apply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
