# Generated by Django 5.0 on 2023-12-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='workmode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
